/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Main_menu3
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        sectionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inputpegawaiPanel = new javax.swing.JPanel();
        inputpegawaiLabel = new javax.swing.JLabel();
        datapegawaiPanel = new javax.swing.JPanel();
        datapegawaiLabel = new javax.swing.JLabel();
        inputmobilPanel = new javax.swing.JPanel();
        inputmobilLabel = new javax.swing.JLabel();
        editmobilPanel = new javax.swing.JPanel();
        editmobilLabel = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        reportLabel = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        titleLabel.setText("RENTAL MOBIL");

        sectionLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        sectionLabel.setText("ADMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(titleLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(sectionLabel)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inputpegawaiPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inputpegawaiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputpegawaiPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputpegawaiPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputpegawaiPanelMouseExited(evt);
            }
        });

        inputpegawaiLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        inputpegawaiLabel.setText("INPUT PEGAWAI");
        inputpegawaiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputpegawaiLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputpegawaiLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputpegawaiLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout inputpegawaiPanelLayout = new javax.swing.GroupLayout(inputpegawaiPanel);
        inputpegawaiPanel.setLayout(inputpegawaiPanelLayout);
        inputpegawaiPanelLayout.setHorizontalGroup(
            inputpegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputpegawaiPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(inputpegawaiLabel)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        inputpegawaiPanelLayout.setVerticalGroup(
            inputpegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputpegawaiPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(inputpegawaiLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        datapegawaiPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        datapegawaiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datapegawaiPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datapegawaiPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datapegawaiPanelMouseExited(evt);
            }
        });

        datapegawaiLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        datapegawaiLabel.setText("DATA PEGAWAI");
        datapegawaiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datapegawaiLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                datapegawaiLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                datapegawaiLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout datapegawaiPanelLayout = new javax.swing.GroupLayout(datapegawaiPanel);
        datapegawaiPanel.setLayout(datapegawaiPanelLayout);
        datapegawaiPanelLayout.setHorizontalGroup(
            datapegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datapegawaiPanelLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(datapegawaiLabel)
                .addGap(70, 70, 70))
        );
        datapegawaiPanelLayout.setVerticalGroup(
            datapegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datapegawaiPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(datapegawaiLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        inputmobilPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inputmobilPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputmobilPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputmobilPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputmobilPanelMouseExited(evt);
            }
        });

        inputmobilLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        inputmobilLabel.setText("INPUT MOBIL");
        inputmobilLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputmobilLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputmobilLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputmobilLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout inputmobilPanelLayout = new javax.swing.GroupLayout(inputmobilPanel);
        inputmobilPanel.setLayout(inputmobilPanelLayout);
        inputmobilPanelLayout.setHorizontalGroup(
            inputmobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputmobilPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(inputmobilLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputmobilPanelLayout.setVerticalGroup(
            inputmobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputmobilPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(inputmobilLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        editmobilPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editmobilPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editmobilPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editmobilPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editmobilPanelMouseExited(evt);
            }
        });

        editmobilLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        editmobilLabel.setText("EDIT MOBIL");
        editmobilLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editmobilLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editmobilLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editmobilLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout editmobilPanelLayout = new javax.swing.GroupLayout(editmobilPanel);
        editmobilPanel.setLayout(editmobilPanelLayout);
        editmobilPanelLayout.setHorizontalGroup(
            editmobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editmobilPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(editmobilLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editmobilPanelLayout.setVerticalGroup(
            editmobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editmobilPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(editmobilLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        reportPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportPanelMouseExited(evt);
            }
        });

        reportLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        reportLabel.setText("REPORT");
        reportLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(reportLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(reportLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        logoutPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutPanelMouseExited(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        logoutLabel.setText("LOGOUT");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(logoutLabel)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logoutLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputmobilPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputpegawaiPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datapegawaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editmobilPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(inputpegawaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(inputmobilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(reportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(datapegawaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(editmobilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datapegawaiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapegawaiPanelMouseClicked
        // TODO add your handling code here:
        new datapegawai().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_datapegawaiPanelMouseClicked

    private void datapegawaiPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapegawaiPanelMouseEntered
        // TODO add your handling code here:
        datapegawaiPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_datapegawaiPanelMouseEntered

    private void datapegawaiPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapegawaiPanelMouseExited
        // TODO add your handling code here:
        datapegawaiPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_datapegawaiPanelMouseExited

    private void datapegawaiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapegawaiLabelMouseClicked
        // TODO add your handling code here:
        new datapegawai().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_datapegawaiLabelMouseClicked

    private void datapegawaiLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapegawaiLabelMouseExited
        // TODO add your handling code here:
        datapegawaiLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_datapegawaiLabelMouseExited

    private void datapegawaiLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datapegawaiLabelMouseEntered
        // TODO add your handling code here:
        datapegawaiLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_datapegawaiLabelMouseEntered

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Yakin mau logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            // Tindakan jika pengguna memilih "Ya"
            new login().setVisible(true);
            this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
        } else {
            // Tindakan jika pengguna memilih "Tidak" atau menutup dialog
            JOptionPane.showMessageDialog(null, "Logout dibatalkan.");
        }
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        // TODO add your handling code here:
        logoutLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        // TODO add your handling code here:
        logoutLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_logoutLabelMouseExited

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Yakin mau logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            // Tindakan jika pengguna memilih "Ya"
            new login().setVisible(true);
            this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
        } else {
            // Tindakan jika pengguna memilih "Tidak" atau menutup dialog
            JOptionPane.showMessageDialog(null, "Logout dibatalkan.");
        }
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void logoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseEntered
        // TODO add your handling code here:
        logoutPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutPanelMouseEntered

    private void logoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseExited
        // TODO add your handling code here:
        logoutPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_logoutPanelMouseExited

    private void inputmobilLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputmobilLabelMouseClicked
        // TODO add your handling code here:
        new inputmobil().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_inputmobilLabelMouseClicked

    private void inputmobilLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputmobilLabelMouseEntered
        // TODO add your handling code here:
        inputmobilLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_inputmobilLabelMouseEntered

    private void inputmobilLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputmobilLabelMouseExited
        // TODO add your handling code here:
        inputmobilLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_inputmobilLabelMouseExited

    private void inputmobilPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputmobilPanelMouseClicked
        // TODO add your handling code here:
        new inputmobil().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_inputmobilPanelMouseClicked

    private void inputmobilPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputmobilPanelMouseEntered
        // TODO add your handling code here:
        inputmobilPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_inputmobilPanelMouseEntered

    private void inputmobilPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputmobilPanelMouseExited
        // TODO add your handling code here:
        inputmobilPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_inputmobilPanelMouseExited

    private void editmobilLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmobilLabelMouseClicked
        // TODO add your handling code here:
        new editmobil().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_editmobilLabelMouseClicked

    private void editmobilLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmobilLabelMouseEntered
        // TODO add your handling code here:
        editmobilLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_editmobilLabelMouseEntered

    private void editmobilLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmobilLabelMouseExited
        // TODO add your handling code here:
        editmobilLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_editmobilLabelMouseExited

    private void editmobilPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmobilPanelMouseClicked
        // TODO add your handling code here:
        new editmobil().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_editmobilPanelMouseClicked

    private void editmobilPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmobilPanelMouseEntered
        // TODO add your handling code here:
        editmobilPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_editmobilPanelMouseEntered

    private void editmobilPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editmobilPanelMouseExited
        // TODO add your handling code here:
        editmobilPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_editmobilPanelMouseExited

    private void reportLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMouseClicked
        // TODO add your handling code here:
        new report().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_reportLabelMouseClicked

    private void reportLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMouseEntered
        // TODO add your handling code here:
        reportLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_reportLabelMouseEntered

    private void reportLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportLabelMouseExited
        // TODO add your handling code here:
        reportLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_reportLabelMouseExited

    private void reportPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPanelMouseClicked
        // TODO add your handling code here:
        new report().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_reportPanelMouseClicked

    private void reportPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPanelMouseEntered
        // TODO add your handling code here:
        reportPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_reportPanelMouseEntered

    private void reportPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPanelMouseExited
        // TODO add your handling code here:
        reportPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_reportPanelMouseExited

    private void inputpegawaiPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputpegawaiPanelMouseExited
        // TODO add your handling code here:
        inputpegawaiPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_inputpegawaiPanelMouseExited

    private void inputpegawaiPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputpegawaiPanelMouseEntered
        // TODO add your handling code here:
        inputpegawaiPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_inputpegawaiPanelMouseEntered

    private void inputpegawaiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputpegawaiPanelMouseClicked
        // TODO add your handling code here:
        new inputpegawai().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_inputpegawaiPanelMouseClicked

    private void inputpegawaiLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputpegawaiLabelMouseExited
        // TODO add your handling code here:
        inputpegawaiLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_inputpegawaiLabelMouseExited

    private void inputpegawaiLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputpegawaiLabelMouseEntered
        // TODO add your handling code here:
        inputpegawaiLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_inputpegawaiLabelMouseEntered

    private void inputpegawaiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputpegawaiLabelMouseClicked
        // TODO add your handling code here:
        new inputpegawai().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_inputpegawaiLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datapegawaiLabel;
    private javax.swing.JPanel datapegawaiPanel;
    private javax.swing.JLabel editmobilLabel;
    private javax.swing.JPanel editmobilPanel;
    private javax.swing.JLabel inputmobilLabel;
    private javax.swing.JPanel inputmobilPanel;
    private javax.swing.JLabel inputpegawaiLabel;
    private javax.swing.JPanel inputpegawaiPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
