/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import code.pegawai;
import code.peminjaman;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Muhammad Ichsan
 */
public class datapegawai extends javax.swing.JFrame {

    /**
     * Creates new form datapegawai
     */
    public datapegawai() {
        initComponents();
        idpegawaiResultField.setEnabled(false);
        namaField.setEnabled(false);
        alamatArea.setEnabled(false);
        cpField.setEnabled(false);
        usernameField.setEnabled(false);
        passField.setEnabled(false);
        kodeComboBox.setEnabled(false);
        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        sectionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        idpegawaiSearchLabel = new javax.swing.JLabel();
        idpegawaiSearchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        idpegawaiResultLabel = new javax.swing.JLabel();
        idpegawaiResultField = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        alamatLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatArea = new javax.swing.JTextArea();
        cpLabel = new javax.swing.JLabel();
        cpField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passField = new javax.swing.JTextField();
        kodeLabel = new javax.swing.JLabel();
        kembaliButton = new javax.swing.JButton();
        kodeComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        titleLabel.setText("RENTAL MOBIL");

        sectionLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        sectionLabel.setText("DATA PEGAWAI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sectionLabel)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        searchLabel.setText("SEARCH");

        idpegawaiSearchLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idpegawaiSearchLabel.setText("ID Pegawai :");

        idpegawaiSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpegawaiSearchFieldActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        resultLabel.setText("RESULT");

        idpegawaiResultLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idpegawaiResultLabel.setText("ID Pegawai :");

        idpegawaiResultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpegawaiResultFieldActionPerformed(evt);
            }
        });

        namaLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        namaLabel.setText("           Nama :");

        alamatLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        alamatLabel.setText("              Alamat :");

        alamatArea.setColumns(20);
        alamatArea.setRows(5);
        jScrollPane1.setViewportView(alamatArea);

        cpLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cpLabel.setText("Contact Person (CP) :");

        cpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpFieldActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        usernameLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        usernameLabel.setText("Username :");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        passLabel.setText("Password :");

        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });

        kodeLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        kodeLabel.setText("Kode :");

        kembaliButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        kembaliButton.setText("KEMBALI");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        kodeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        kodeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alamatLabel)
                            .addComponent(namaLabel)
                            .addComponent(idpegawaiResultLabel)
                            .addComponent(idpegawaiSearchLabel)
                            .addComponent(cpLabel)
                            .addComponent(usernameLabel)
                            .addComponent(passLabel)
                            .addComponent(kodeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idpegawaiResultField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(namaField)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(cpField)
                                    .addComponent(idpegawaiSearchField)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(updateButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteButton)))
                                .addGap(18, 18, 18)
                                .addComponent(searchButton))
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(searchLabel)
                    .addComponent(resultLabel))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kembaliButton))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(searchLabel)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpegawaiSearchLabel)
                    .addComponent(idpegawaiSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(20, 20, 20)
                .addComponent(resultLabel)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpegawaiResultLabel)
                    .addComponent(idpegawaiResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alamatLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpLabel)
                    .addComponent(cpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeLabel)
                    .addComponent(kodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addGap(35, 35, 35)
                .addComponent(kembaliButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean hasPeminjaman(String idPegawai) throws SQLException {
        peminjaman pem = new peminjaman();
        pem.setPeg(idPegawai);
        pem.r = pem.getPeminjamanPeg();
        if(pem.r.next()){
            return true;
        }
        else{
            return false;
        }
    }
    
    private void idpegawaiSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpegawaiSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpegawaiSearchFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(idpegawaiSearchField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
            idpegawaiSearchField.requestFocus();
        }   
        else{
            pegawai peg = new pegawai();
            peg.setIdbaru(idpegawaiSearchField.getText());
            try{
                peg.r =  peg.getPegawai();
                while(peg.r.next()){
                    idpegawaiResultField.setText(peg.r.getString("id_pegawai"));
                    namaField.setText(peg.r.getString("nama"));
                    alamatArea.setText(peg.r.getString("alamat"));
                    cpField.setText(peg.r.getString("cp"));
                    usernameField.setText(peg.r.getString("username"));
                    passField.setText(peg.r.getString("password"));
                    if(peg.r.getString("kode").equals("0")){
                        kodeComboBox.setSelectedItem("User");
                    }
                    else{
                        kodeComboBox.setSelectedItem("Admin");
                    }
                    javax.swing.JOptionPane.showMessageDialog(null, "Search Success");
                    
                    idpegawaiSearchField.setEnabled(false);
                    idpegawaiResultField.setEnabled(true);
                    namaField.setEnabled(true);
                    alamatArea.setEnabled(true);
                    cpField.setEnabled(true);
                    usernameField.setEnabled(true);
                    passField.setEnabled(true);
                    kodeComboBox.setEnabled(true);
                    updateButton.setEnabled(true);
                    deleteButton.setEnabled(true);
                }
                peg.r.close();
                
                String idPegawai = idpegawaiSearchField.getText();
                try {
                    if (hasPeminjaman(idPegawai)) {
                        javax.swing.JOptionPane.showMessageDialog(null, "Kode & ID pegawai tidak bisa diubah karena sedang mengurus peminjaman");
                        idpegawaiResultField.setEnabled(false);
                        kodeComboBox.setEnabled(false);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(datapegawai.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void idpegawaiResultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpegawaiResultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpegawaiResultFieldActionPerformed

    private void cpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if (idpegawaiResultField.getText().isEmpty() || namaField.getText().isEmpty() || alamatArea.getText().isEmpty() || cpField.getText().isEmpty() || usernameField.getText().isEmpty() || passField.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
        }      
        else
        {
            idpegawaiResultField.setEnabled(false);
            namaField.setEnabled(false);
            alamatArea.setEnabled(false);
            cpField.setEnabled(false);
            usernameField.setEnabled(false);
            passField.setEnabled(false);
            kodeComboBox.setEnabled(false);
            updateButton.setEnabled(false);
            deleteButton.setEnabled(false);

            pegawai peg = new pegawai();
            peg.setIdbaru(idpegawaiResultField.getText());
            peg.setIdlama(idpegawaiSearchField.getText());   
            peg.setNama(namaField.getText());
            peg.setAlamat(alamatArea.getText());
            peg.setCp(cpField.getText());
            peg.setUsername(usernameField.getText());
            peg.setPassword(passField.getText());
            if(kodeComboBox.getSelectedItem() == "User"){
                peg.setKode("0");
            }
            else{
                peg.setKode("1");
            }

            peg.updatePegawai();

            javax.swing.JOptionPane.showMessageDialog(null, "Update Success");

            idpegawaiSearchField.setEnabled(true);
            idpegawaiSearchField.setText(null);
            idpegawaiSearchField.requestFocus();
            idpegawaiResultField.setText(null);
            namaField.setText(null);
            alamatArea.setText(null);
            cpField.setText(null);
            usernameField.setText(null);
            passField.setText(null);
            kodeComboBox.setSelectedItem("User");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (idpegawaiResultField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
        }  
        else
        {
            String idPegawai = idpegawaiResultField.getText();
            try {
                if (hasPeminjaman(idPegawai)) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Tidak dapat menghapus pegawai karena sedang mengurus peminjaman");
                    return;
                }
                else{
                    idpegawaiResultField.setEnabled(false);
                    namaField.setEnabled(false);
                    alamatArea.setEnabled(false);
                    cpField.setEnabled(false);
                    usernameField.setEnabled(false);
                    passField.setEnabled(false);
                    kodeComboBox.setEnabled(false);
                    updateButton.setEnabled(false);
                    deleteButton.setEnabled(false);
                    
                    pegawai peg = new pegawai();
                    peg.setIdbaru(idpegawaiResultField.getText());
                    peg.setNama(namaField.getText());
                    peg.setAlamat(alamatArea.getText());
                    peg.setCp(cpField.getText());
                    peg.setUsername(usernameField.getText());
                    peg.setPassword(passField.getText());
                    
                    peg.deletePegawai();
                    
                    javax.swing.JOptionPane.showMessageDialog(null, "Delete Success");
                    
                    idpegawaiSearchField.setEnabled(true);
                    idpegawaiSearchField.setText(null);
                    idpegawaiSearchField.requestFocus();
                    idpegawaiResultField.setText(null);
                    namaField.setText(null);
                    alamatArea.setText(null);
                    cpField.setText(null);
                    usernameField.setText(null);
                    passField.setText(null);
                    kodeComboBox.setSelectedItem("User");
                }
            } catch (SQLException ex) {
                Logger.getLogger(datapegawai.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        new Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    private void kodeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datapegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatArea;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextField cpField;
    private javax.swing.JLabel cpLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField idpegawaiResultField;
    private javax.swing.JLabel idpegawaiResultLabel;
    private javax.swing.JTextField idpegawaiSearchField;
    private javax.swing.JLabel idpegawaiSearchLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JComboBox<String> kodeComboBox;
    private javax.swing.JLabel kodeLabel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
