/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import code.mobil;
import code.peminjaman;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Muhammad Ichsan
 */
public class editmobil extends javax.swing.JFrame {

    /**
     * Creates new form editmobil
     */
    public editmobil() {
        initComponents();
        idmobilResultField.setEnabled(false);
        jenisField.setEnabled(false);
        sewaField.setEnabled(false);
        stokField.setEnabled(false);
        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        sectionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        idmobilSearchLabel = new javax.swing.JLabel();
        idmobilSearchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        idmobilResultLabel = new javax.swing.JLabel();
        idmobilResultField = new javax.swing.JTextField();
        jenisLabel = new javax.swing.JLabel();
        jenisField = new javax.swing.JTextField();
        sewaLabel = new javax.swing.JLabel();
        sewaField = new javax.swing.JTextField();
        perhariLabel = new javax.swing.JLabel();
        stokLabel = new javax.swing.JLabel();
        stokField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        kembaliButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        titleLabel.setText("RENTAL MOBIL");

        sectionLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        sectionLabel.setText("EDIT MOBIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(titleLabel)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sectionLabel)
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        searchLabel.setText("SEARCH");

        idmobilSearchLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idmobilSearchLabel.setText("ID Mobil :");

        idmobilSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmobilSearchFieldActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        resultLabel.setText("RESULT");

        idmobilResultLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idmobilResultLabel.setText("ID Mobil :");

        idmobilResultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmobilResultFieldActionPerformed(evt);
            }
        });

        jenisLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jenisLabel.setText("           Jenis :");

        jenisField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisFieldActionPerformed(evt);
            }
        });

        sewaLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        sewaLabel.setText("Harga Sewa :");

        sewaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sewaFieldActionPerformed(evt);
            }
        });

        perhariLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        perhariLabel.setText("per hari");

        stokLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        stokLabel.setText("Stok :");

        stokField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokFieldActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        kembaliButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        kembaliButton.setText("KEMBALI");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(idmobilSearchLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(idmobilSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(idmobilResultLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(idmobilResultField))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sewaLabel)
                                    .addComponent(jenisLabel)
                                    .addComponent(stokLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(updateButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteButton))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jenisField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(sewaField)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(perhariLabel))
                                        .addComponent(stokField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(searchButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchLabel)
                            .addComponent(resultLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kembaliButton))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(searchLabel)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idmobilSearchLabel)
                    .addComponent(idmobilSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(20, 20, 20)
                .addComponent(resultLabel)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idmobilResultLabel)
                    .addComponent(idmobilResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisLabel)
                    .addComponent(jenisField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sewaLabel)
                    .addComponent(sewaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perhariLabel))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stokLabel)
                    .addComponent(stokField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(kembaliButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean hasPeminjaman(String idMobil) throws SQLException {
        peminjaman pem = new peminjaman();
        pem.setMobil(idMobil);
        pem.r = pem.getPeminjamanMobil();
        if(pem.r.next()){
            return true;
        }
        else{
            return false;
        }
    }
    
    private boolean isNumeric(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private void idmobilSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmobilSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idmobilSearchFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(idmobilSearchField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
            idmobilSearchField.requestFocus();
        }
        else{
            mobil mob = new mobil();
            mob.setIdbaru(idmobilSearchField.getText());
            try{
                mob.r =  mob.getMobilId();
                while(mob.r.next()){
                    idmobilResultField.setText(mob.r.getString("id_mobil"));
                    jenisField.setText(mob.r.getString("jenis"));
                    sewaField.setText(mob.r.getString("sewa"));
                    stokField.setText(mob.r.getString("stok"));
                    javax.swing.JOptionPane.showMessageDialog(null, "Search Success");

                    idmobilSearchField.setEnabled(false);
                    idmobilResultField.setEnabled(true);
                    jenisField.setEnabled(true);
                    sewaField.setEnabled(true);
                    stokField.setEnabled(true);
                    updateButton.setEnabled(true);
                    deleteButton.setEnabled(true);
                }
                mob.r.close();
                String idMobil = idmobilSearchField.getText();
                try {
                    if (hasPeminjaman(idMobil)) {
                        javax.swing.JOptionPane.showMessageDialog(null, "ID mobil tidak bisa diubah karena mobil sedang dipinjam");
                        idmobilResultField.setEnabled(false);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(datapegawai.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void idmobilResultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmobilResultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idmobilResultFieldActionPerformed

    private void jenisFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisFieldActionPerformed

    private void sewaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sewaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sewaFieldActionPerformed

    private void stokFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stokFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        if (idmobilResultField.getText().isEmpty() || jenisField.getText().isEmpty() || sewaField.getText().isEmpty() || stokField.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
        }      
        else
        {
            mobil mob = new mobil();
            mob.setIdbaru(idmobilResultField.getText());
            mob.setIdlama(idmobilSearchField.getText());
            mob.setJenis(jenisField.getText());

            String Text = sewaField.getText();
            if (isNumeric(Text)) {
                mob.setSewa(Integer.parseInt(Text));
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Masukkan Angka Pada Harga Sewa");
                sewaField.setText(null);
                sewaField.requestFocus();
                return;
            }

            Text = stokField.getText();
            if (isNumeric(Text)) {
                mob.setStok(Integer.parseInt(Text));
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Masukkan Angka Pada Stok");
                stokField.setText(null);
                stokField.requestFocus();
                return;
            }
            
            mob.updateMobil();

            javax.swing.JOptionPane.showMessageDialog(null, "Update Success");

            idmobilResultField.setEnabled(false);
            jenisField.setEnabled(false);
            sewaField.setEnabled(false);
            stokField.setEnabled(false);
            updateButton.setEnabled(false);
            deleteButton.setEnabled(false);
            
            idmobilSearchField.setEnabled(true);
            idmobilSearchField.setText(null);
            idmobilSearchField.requestFocus();
            idmobilResultField.setText(null);
            jenisField.setText(null);
            sewaField.setText(null);
            stokField.setText(null);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (idmobilResultField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
        }  
        else
        {
            String idmobil = idmobilResultField.getText();
            try {
                if (hasPeminjaman(idmobil)) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Tidak dapat menghapus mobil karena mobil sedang dipinjam");
                    return;
                }
                else{
                    idmobilResultField.setEnabled(false);
                    jenisField.setEnabled(false);
                    sewaField.setEnabled(false);
                    stokField.setEnabled(false);
                    updateButton.setEnabled(false);
                    deleteButton.setEnabled(false);

                    mobil mob = new mobil();
                    mob.setIdbaru(idmobilResultField.getText());
                    mob.setIdlama(idmobilSearchField.getText());
                    mob.setJenis(jenisField.getText());
                    mob.setSewa(Integer.parseInt(sewaField.getText()));
                    mob.setStok(Integer.parseInt(stokField.getText()));

                    mob.deleteMobil();

                    javax.swing.JOptionPane.showMessageDialog(null, "Delete Success");

                    idmobilSearchField.setEnabled(true);
                    idmobilSearchField.setText(null);
                    idmobilSearchField.requestFocus();
                    idmobilResultField.setText(null);
                    jenisField.setText(null);
                    sewaField.setText(null);
                    stokField.setText(null);
                }
            } catch (SQLException ex) {
                Logger.getLogger(datapegawai.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        new Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editmobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editmobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editmobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editmobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editmobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField idmobilResultField;
    private javax.swing.JLabel idmobilResultLabel;
    private javax.swing.JTextField idmobilSearchField;
    private javax.swing.JLabel idmobilSearchLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jenisField;
    private javax.swing.JLabel jenisLabel;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JLabel perhariLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JTextField sewaField;
    private javax.swing.JLabel sewaLabel;
    private javax.swing.JTextField stokField;
    private javax.swing.JLabel stokLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
