/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import code.mobil;
import code.peminjaman;
import code.pegawai;
import code.pelanggan;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Muhammad Ichsan
 */
public class peminjamanUI extends javax.swing.JFrame {

    /**
     * Creates new form peminjamanUI
     */
    public peminjamanUI() {
        initComponents();
        saveButton.setEnabled(false);
        biayasewaField.setEnabled(false);
        lamapinjamField.setEnabled(false);
        totalsewaField.setEnabled(false);
        idpegawaiField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        sectionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        idpegawaiLabel = new javax.swing.JLabel();
        idpegawaiField = new javax.swing.JTextField();
        idpeminjamanLabel = new javax.swing.JLabel();
        idpeminjamanField = new javax.swing.JTextField();
        idpelangganLabel = new javax.swing.JLabel();
        idpelangganField = new javax.swing.JTextField();
        idmobilLabel = new javax.swing.JLabel();
        idmobilField = new javax.swing.JTextField();
        tglpinjamLabel = new javax.swing.JLabel();
        tglpinjamDate = new com.toedter.calendar.JDateChooser();
        tglkembaliLabel = new javax.swing.JLabel();
        tglkembaliDate = new com.toedter.calendar.JDateChooser();
        generateButton = new javax.swing.JButton();
        biayasewaLabel = new javax.swing.JLabel();
        biayasewaField = new javax.swing.JTextField();
        perhariLabel = new javax.swing.JLabel();
        lamapinjamLabel = new javax.swing.JLabel();
        lamapinjamField = new javax.swing.JTextField();
        hariLabel = new javax.swing.JLabel();
        totalsewaLabel = new javax.swing.JLabel();
        totalsewaField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        kembaliButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        titleLabel.setText("RENTAL MOBIL");

        sectionLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        sectionLabel.setText("PEMINJAMAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(sectionLabel)
                .addGap(255, 255, 255))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        idpegawaiLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idpegawaiLabel.setText("        ID Pegawai :");

        idpegawaiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpegawaiFieldActionPerformed(evt);
            }
        });

        idpeminjamanLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idpeminjamanLabel.setText("  ID Peminjaman :");

        idpeminjamanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpeminjamanFieldActionPerformed(evt);
            }
        });

        idpelangganLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idpelangganLabel.setText("   ID Pelanggan :");

        idpelangganField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpelangganFieldActionPerformed(evt);
            }
        });

        idmobilLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idmobilLabel.setText("          ID Mobil :");

        idmobilField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmobilFieldActionPerformed(evt);
            }
        });

        tglpinjamLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tglpinjamLabel.setText("Tanggal Pinjam :");

        tglkembaliLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tglkembaliLabel.setText("Tanggal Kembali :");

        generateButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        generateButton.setText("GENERATE");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        biayasewaLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        biayasewaLabel.setText("Biaya Sewa :");

        biayasewaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayasewaFieldActionPerformed(evt);
            }
        });

        perhariLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        perhariLabel.setText("per hari");

        lamapinjamLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lamapinjamLabel.setText("Lama Pinjam :");

        lamapinjamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamapinjamFieldActionPerformed(evt);
            }
        });

        hariLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        hariLabel.setText("hari");

        totalsewaLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        totalsewaLabel.setText("   Total Sewa :");

        totalsewaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalsewaFieldActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        kembaliButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        kembaliButton.setText("KEMBALI");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idpegawaiLabel)
                            .addComponent(idpeminjamanLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idpegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idpeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idmobilLabel)
                            .addComponent(idpelangganLabel)
                            .addComponent(tglpinjamLabel)
                            .addComponent(tglkembaliLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generateButton)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idpelangganField)
                                .addComponent(tglpinjamDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tglkembaliDate, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(idmobilField)))))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lamapinjamLabel)
                    .addComponent(biayasewaLabel)
                    .addComponent(totalsewaLabel)
                    .addComponent(saveButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lamapinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(biayasewaField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perhariLabel)
                            .addComponent(hariLabel))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalsewaField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kembaliButton))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpegawaiLabel)
                    .addComponent(idpegawaiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biayasewaLabel)
                    .addComponent(perhariLabel)
                    .addComponent(biayasewaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpeminjamanLabel)
                    .addComponent(idpeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lamapinjamLabel)
                    .addComponent(lamapinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hariLabel))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpelangganLabel)
                    .addComponent(idpelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalsewaLabel)
                    .addComponent(totalsewaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idmobilLabel)
                    .addComponent(saveButton)
                    .addComponent(cancelButton)
                    .addComponent(idmobilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglpinjamLabel)
                    .addComponent(tglpinjamDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tglkembaliLabel)
                    .addComponent(tglkembaliDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(generateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(kembaliButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private static long daysBetween(Calendar startDate, Calendar endDate) {
        long millisecondsPerDay = 24 * 60 * 60 * 1000;
        long startMillis = startDate.getTimeInMillis();
        long endMillis = endDate.getTimeInMillis();
        return (endMillis - startMillis) / millisecondsPerDay;
    }
    
    private void idpegawaiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpegawaiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpegawaiFieldActionPerformed

    private void idpeminjamanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpeminjamanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpeminjamanFieldActionPerformed

    private void idpelangganFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpelangganFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpelangganFieldActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
    if (idpegawaiField.getText().isEmpty() || idpeminjamanField.getText().isEmpty() || idpelangganField.getText().isEmpty() || idmobilField.getText().isEmpty() || tglpinjamDate.getDate() == null || tglkembaliDate.getDate() == null){
        javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
    }
    else{
        mobil mob = new mobil();
        mob.setIdbaru(idmobilField.getText());
        pegawai peg = new pegawai();
        peg.setIdbaru(idpegawaiField.getText());
        pelanggan pel = new pelanggan();
        pel.setId(idpelangganField.getText());
        peminjaman pem = new peminjaman();
        pem.setPem(idpeminjamanField.getText());
        try {
            mob.r = mob.getMobilId();
            peg.r = peg.getPegawai();
            pel.r = pel.getPelanggan();
            pem.r = pem.getPeminjamanId();
            
            if (!peg.r.next()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Data Pegawai tidak ditemukan");
                idpegawaiField.setText(null);
                idpegawaiField.requestFocus();
                return; 
            }
            
            if (!pel.r.next()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Data Pelanggan tidak ditemukan");
                idpelangganField.setText(null);
                idpelangganField.requestFocus();
                return;
            }
            
            if (!mob.r.next()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Data Mobil tidak ditemukan");
                idmobilField.setText(null);
                idmobilField.requestFocus();
                return;
            }
            
            if (pem.r.next()) {
                javax.swing.JOptionPane.showMessageDialog(null, "Terdapat Duplikat Data (id_peminjaman)");
                idpeminjamanField.setText(null);
                idpeminjamanField.requestFocus();
                return;
            }

            if ("0".equals(mob.r.getString("stok"))) {
                javax.swing.JOptionPane.showMessageDialog(null, "Stok Mobil Kosong");
                idmobilField.setText(null);
                return;
            }

            do {
                Calendar calPinjam = Calendar.getInstance();
                calPinjam.setTime(tglpinjamDate.getDate());

                Calendar calKembali = Calendar.getInstance();
                calKembali.setTime(tglkembaliDate.getDate());

                if (calKembali.before(calPinjam)) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Tanggal Kembali < Tanggal Pinjam");
                    tglpinjamDate.setDate(null);
                    tglkembaliDate.setDate(null);
                    tglpinjamDate.requestFocus();
                    return;
                }
                
                long lamasewa = daysBetween(calPinjam, calKembali);
                biayasewaField.setText(mob.r.getString("sewa"));
                lamapinjamField.setText(String.valueOf(lamasewa));
                totalsewaField.setText(String.valueOf(lamasewa * Integer.parseInt(mob.r.getString("sewa"))));              
            } while(mob.r.next());

            saveButton.setEnabled(true);
            cancelButton.setEnabled(true);
            mob.r.close();
            } catch(Exception e){
                javax.swing.JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
            }
        }
    }//GEN-LAST:event_generateButtonActionPerformed

    private void totalsewaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalsewaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalsewaFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        int stok = 0;
        
        peminjaman pem = new peminjaman();
        Date pinjam = tglpinjamDate.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String formattedDatepinjam = sdf.format(pinjam);
        Date kembali = tglkembaliDate.getDate();
        String formattedDatekembali = sdf.format(kembali);
        
        pem.setPem(idpeminjamanField.getText());
        pem.setPeg(idpegawaiField.getText());
        pem.setMobil(idmobilField.getText());
        pem.setPel(idpelangganField.getText());
        pem.setTglpinjam(formattedDatepinjam);
        pem.setTglkembali(formattedDatekembali);
        pem.setLama(lamapinjamField.getText());
        pem.setBiaya(totalsewaField.getText());
        pem.setStatus("Masih Dipinjam");
        pem.insertPeminjaman();
        javax.swing.JOptionPane.showMessageDialog(null, "Insert Success");
        
        mobil mob = new mobil();
        mob.setIdbaru(idmobilField.getText());
        mob.r = mob.getMobilId();
        try {
            while (mob.r.next()) {
                stok = mob.r.getInt("stok") - 1;

                mob.setStok(stok);
                mob.updateStokMobil();
            }
        } catch (SQLException ex) {
            Logger.getLogger(peminjamanUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        idpegawaiField.setText(null);
        idpeminjamanField.setText(null);
        idpelangganField.setText(null);
        idmobilField.setText(null);
        tglpinjamDate.setDate(null);
        tglkembaliDate.setDate(null);
        biayasewaField.setText(null);
        lamapinjamField.setText(null);
        totalsewaField.setText(null);
        saveButton.setEnabled(false);
        idpegawaiField.requestFocus();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        saveButton.setEnabled(false);
        idpegawaiField.setText(null) ;
        idpeminjamanField.setText(null);
        idpelangganField.setText(null) ;
        idmobilField.setText(null);
        tglpinjamDate.setDate(null);
        tglkembaliDate.setDate(null);
        biayasewaField.setText(null);
        lamapinjamField.setText(null) ;
        totalsewaField.setText(null);
        idpegawaiField.requestFocus();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void biayasewaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayasewaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biayasewaFieldActionPerformed

    private void lamapinjamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamapinjamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamapinjamFieldActionPerformed

    private void idmobilFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmobilFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idmobilFieldActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        new User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peminjamanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peminjamanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peminjamanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peminjamanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peminjamanUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biayasewaField;
    private javax.swing.JLabel biayasewaLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton generateButton;
    private javax.swing.JLabel hariLabel;
    private javax.swing.JTextField idmobilField;
    private javax.swing.JLabel idmobilLabel;
    private javax.swing.JTextField idpegawaiField;
    private javax.swing.JLabel idpegawaiLabel;
    private javax.swing.JTextField idpelangganField;
    private javax.swing.JLabel idpelangganLabel;
    private javax.swing.JTextField idpeminjamanField;
    private javax.swing.JLabel idpeminjamanLabel;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JTextField lamapinjamField;
    private javax.swing.JLabel lamapinjamLabel;
    private javax.swing.JLabel perhariLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sectionLabel;
    private com.toedter.calendar.JDateChooser tglkembaliDate;
    private javax.swing.JLabel tglkembaliLabel;
    private com.toedter.calendar.JDateChooser tglpinjamDate;
    private javax.swing.JLabel tglpinjamLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField totalsewaField;
    private javax.swing.JLabel totalsewaLabel;
    // End of variables declaration//GEN-END:variables
}
