/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import code.mobil;
import code.peminjaman;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Muhammad Ichsan
 */
public class pengembalian extends javax.swing.JFrame {

    /**
     * Creates new form pengembalian
     */
    public pengembalian() {
        initComponents();
        processButton.setEnabled(false);
        saveButton.setEnabled(false);
        telatField.setEnabled(false);
        dendaField.setEnabled(false);
        idpelangganField.setEnabled(false);
        idmobilField.setEnabled(false);
        tglpinjamField.setEnabled(false);
        lamapinjamField.setEnabled(false);
        totalsewaField.setEnabled(false);
        tglkembaliField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        sectionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        idpeminjamanLabel = new javax.swing.JLabel();
        idpeminjamanField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        idmobilField = new javax.swing.JTextField();
        idmobilLabel = new javax.swing.JLabel();
        idpelangganField = new javax.swing.JTextField();
        idpelangganLabel = new javax.swing.JLabel();
        tglpinjamLabel = new javax.swing.JLabel();
        tglpinjamField = new javax.swing.JTextField();
        tglkembaliLabel = new javax.swing.JLabel();
        tglkembaliField = new javax.swing.JTextField();
        lamapinjamLabel = new javax.swing.JLabel();
        lamapinjamField = new javax.swing.JTextField();
        totalsewaLabel = new javax.swing.JLabel();
        totalsewaField = new javax.swing.JTextField();
        haripinjamLabel = new javax.swing.JLabel();
        telatLabel = new javax.swing.JLabel();
        telatField = new javax.swing.JTextField();
        haritelatLabel = new javax.swing.JLabel();
        processButton = new javax.swing.JButton();
        dendaLabel = new javax.swing.JLabel();
        dendaField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        kembaliButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        titleLabel.setText("RENTAL MOBIL");

        sectionLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        sectionLabel.setText("PENGEMBALIAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sectionLabel)
                .addGap(177, 177, 177))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        searchLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        searchLabel.setText("SEARCH");

        idpeminjamanLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idpeminjamanLabel.setText("ID Peminjaman :");

        idpeminjamanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpeminjamanFieldActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resultLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        resultLabel.setText("RESULT");

        idmobilField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmobilFieldActionPerformed(evt);
            }
        });

        idmobilLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idmobilLabel.setText("          ID Mobil :");

        idpelangganField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpelangganFieldActionPerformed(evt);
            }
        });

        idpelangganLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        idpelangganLabel.setText("   ID Pelanggan :");

        tglpinjamLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tglpinjamLabel.setText("Tanggal Pinjam :");

        tglpinjamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglpinjamFieldActionPerformed(evt);
            }
        });

        tglkembaliLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tglkembaliLabel.setText("Tanggal Kembali :");

        tglkembaliField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglkembaliFieldActionPerformed(evt);
            }
        });

        lamapinjamLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lamapinjamLabel.setText("Lama Pinjam :");

        lamapinjamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lamapinjamFieldActionPerformed(evt);
            }
        });

        totalsewaLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        totalsewaLabel.setText("   Total Sewa :");

        totalsewaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalsewaFieldActionPerformed(evt);
            }
        });

        haripinjamLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        haripinjamLabel.setText("hari");

        telatLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        telatLabel.setText("             Telat :");

        telatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telatFieldActionPerformed(evt);
            }
        });

        haritelatLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        haritelatLabel.setText("hari");

        processButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        processButton.setText("PROCESS");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        dendaLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        dendaLabel.setText("             Denda :");

        dendaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dendaFieldActionPerformed(evt);
            }
        });

        saveButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        kembaliButton.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        kembaliButton.setText("KEMBALI");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idpelangganLabel)
                            .addComponent(idpeminjamanLabel)
                            .addComponent(idmobilLabel)
                            .addComponent(tglpinjamLabel)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(totalsewaLabel)
                                .addComponent(lamapinjamLabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(telatLabel)
                                    .addComponent(tglkembaliLabel)
                                    .addComponent(dendaLabel))
                                .addGap(1, 1, 1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(idpeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton))
                            .addComponent(idpelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idmobilField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lamapinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(haripinjamLabel))
                            .addComponent(totalsewaField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(telatField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(haritelatLabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dendaField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(processButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(saveButton))
                            .addComponent(tglpinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglkembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(kembaliButton))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(searchLabel)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpeminjamanLabel)
                    .addComponent(idpeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(20, 20, 20)
                .addComponent(resultLabel)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idpelangganLabel)
                    .addComponent(idpelangganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idmobilLabel)
                    .addComponent(idmobilField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglpinjamLabel)
                    .addComponent(tglpinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lamapinjamLabel)
                    .addComponent(lamapinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haripinjamLabel))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalsewaLabel)
                    .addComponent(totalsewaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglkembaliLabel)
                    .addComponent(tglkembaliField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telatLabel)
                    .addComponent(telatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(haritelatLabel))
                .addGap(20, 20, 20)
                .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dendaLabel)
                    .addComponent(dendaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(kembaliButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idpeminjamanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpeminjamanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpeminjamanFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(idpeminjamanField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
            idpeminjamanField.requestFocus();
        }
        
        else{
            peminjaman pem = new peminjaman();
            pem.setPem(idpeminjamanField.getText());
            try{
                pem.r =  pem.getPeminjamanId();
                while(pem.r.next()){
                    if(pem.r.getString("status").equals("Telah Dikembalikan")){
                        javax.swing.JOptionPane.showMessageDialog(null, "Mobil Telah Dikembalikan");
                        idpeminjamanField.setText(null);
                        idpelangganField.setText(null);
                        idmobilField.setText(null);
                        tglpinjamField.setText(null);
                        lamapinjamField.setText(null);
                        totalsewaField.setText(null);
                        tglkembaliField.setText(null);
                        telatField.setText(null);
                        dendaField.setText(null);
                        telatField.setEnabled(false);
                        processButton.setEnabled(false);
                        saveButton.setEnabled(false);
                        idpeminjamanField.requestFocus();
                        return;
                    }
                    
                    idpelangganField.setText(pem.r.getString("id_pelanggan"));
                    idmobilField.setText(pem.r.getString("id_mobil"));
                    tglpinjamField.setText(pem.r.getString("tgl_pinjam"));
                    lamapinjamField.setText(String.valueOf(pem.r.getInt("lama") ));
                    totalsewaField.setText(String.valueOf(pem.r.getInt("biaya" )));
                    tglkembaliField.setText(pem.r.getString("tgl_hrs_kembali"));
                    javax.swing.JOptionPane.showMessageDialog(null, "Search Success");
                    telatField.setText(null);
                    dendaField.setText(null);
                    telatField.setEnabled(true);
                    processButton.setEnabled(true);
                    saveButton.setEnabled(false);
                } 
                pem.r.close();
            }
                catch(Exception e){
                    javax.swing.JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
                }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void idmobilFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmobilFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idmobilFieldActionPerformed

    private void idpelangganFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpelangganFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpelangganFieldActionPerformed

    private void lamapinjamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lamapinjamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lamapinjamFieldActionPerformed

    private void totalsewaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalsewaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalsewaFieldActionPerformed

    private void telatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telatFieldActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        // TODO add your handling code here:
        if(telatField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "Harap isi semua kolom yang diperlukan");
            telatField.requestFocus();
        }
        
        else{
            int k, l;
            k = Integer.valueOf(telatField.getText()).intValue();
            l = k * 100000;
            dendaField.setText(String.valueOf(l));
            saveButton.setEnabled(true);
        }
    }//GEN-LAST:event_processButtonActionPerformed

    private void dendaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dendaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dendaFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        int stok = 0;
        
        peminjaman pem = new peminjaman();
        pem.setPem(idpeminjamanField.getText());
        pem.setTelat(telatField.getText());
        pem.setDenda(dendaField.getText());
        pem.setStatus("Telah Dikembalikan");
        pem.updatePeminjaman();
        javax.swing.JOptionPane.showMessageDialog(null, "Update Success");
        
        mobil mob = new mobil();
        mob.setIdbaru(idmobilField.getText());
        mob.r = mob.getMobilId();
        try {
            while (mob.r.next()) {
                stok = mob.r.getInt("stok") + 1 ;
                mob.setStok(stok);
                mob.updateStokMobil();
            }
        } catch (SQLException ex) {
            Logger.getLogger(peminjamanUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        idpeminjamanField.setText(null);
        idpelangganField.setText(null);
        idmobilField.setText(null);
        tglpinjamField.setText(null);
        lamapinjamField.setText(null);
        totalsewaField.setText(null);
        tglkembaliField.setText(null);
        telatField.setText(null);
        dendaField.setText(null);
        idpeminjamanField.requestFocus();
        telatField.setEnabled(false);
        processButton.setEnabled(false);
        saveButton.setEnabled(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void tglpinjamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglpinjamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglpinjamFieldActionPerformed

    private void tglkembaliFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglkembaliFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglkembaliFieldActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        // TODO add your handling code here:
        new User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kembaliButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dendaField;
    private javax.swing.JLabel dendaLabel;
    private javax.swing.JLabel haripinjamLabel;
    private javax.swing.JLabel haritelatLabel;
    private javax.swing.JTextField idmobilField;
    private javax.swing.JLabel idmobilLabel;
    private javax.swing.JTextField idpelangganField;
    private javax.swing.JLabel idpelangganLabel;
    private javax.swing.JTextField idpeminjamanField;
    private javax.swing.JLabel idpeminjamanLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JTextField lamapinjamField;
    private javax.swing.JLabel lamapinjamLabel;
    private javax.swing.JButton processButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JTextField telatField;
    private javax.swing.JLabel telatLabel;
    private javax.swing.JTextField tglkembaliField;
    private javax.swing.JLabel tglkembaliLabel;
    private javax.swing.JTextField tglpinjamField;
    private javax.swing.JLabel tglpinjamLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField totalsewaField;
    private javax.swing.JLabel totalsewaLabel;
    // End of variables declaration//GEN-END:variables
}
