/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form Main_menu3
     */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        sectionLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        inputPanel = new javax.swing.JPanel();
        inputLabel = new javax.swing.JLabel();
        dataPanel = new javax.swing.JPanel();
        dataLabel = new javax.swing.JLabel();
        mobilPanel = new javax.swing.JPanel();
        mobilLabel = new javax.swing.JLabel();
        peminjamanPanel = new javax.swing.JPanel();
        peminjamanLabel = new javax.swing.JLabel();
        pengembalianPanel = new javax.swing.JPanel();
        pengembalianLabel = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titleLabel.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        titleLabel.setText("RENTAL MOBIL");

        sectionLabel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        sectionLabel.setText("USER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(titleLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(sectionLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inputPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        inputPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputPanelMouseExited(evt);
            }
        });

        inputLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        inputLabel.setText("INPUT PELANGGAN");
        inputLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(inputLabel)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(inputLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        dataPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dataPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataPanelMouseExited(evt);
            }
        });

        dataLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        dataLabel.setText("DATA PELANGGAN");
        dataLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dataLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dataLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(dataLabel)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(dataLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mobilPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mobilPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mobilPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mobilPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mobilPanelMouseExited(evt);
            }
        });

        mobilLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        mobilLabel.setText("MOBIL");
        mobilLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mobilLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mobilLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mobilLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mobilPanelLayout = new javax.swing.GroupLayout(mobilPanel);
        mobilPanel.setLayout(mobilPanelLayout);
        mobilPanelLayout.setHorizontalGroup(
            mobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mobilPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(mobilLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mobilPanelLayout.setVerticalGroup(
            mobilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mobilPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(mobilLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        peminjamanPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        peminjamanPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peminjamanPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                peminjamanPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                peminjamanPanelMouseExited(evt);
            }
        });

        peminjamanLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        peminjamanLabel.setText("PEMINJAMAN");
        peminjamanLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peminjamanLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                peminjamanLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                peminjamanLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout peminjamanPanelLayout = new javax.swing.GroupLayout(peminjamanPanel);
        peminjamanPanel.setLayout(peminjamanPanelLayout);
        peminjamanPanelLayout.setHorizontalGroup(
            peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(peminjamanLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        peminjamanPanelLayout.setVerticalGroup(
            peminjamanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peminjamanPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(peminjamanLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pengembalianPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pengembalianPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengembalianPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pengembalianPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pengembalianPanelMouseExited(evt);
            }
        });

        pengembalianLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        pengembalianLabel.setText("PENGEMBALIAN");
        pengembalianLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pengembalianLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pengembalianLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pengembalianLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pengembalianPanelLayout = new javax.swing.GroupLayout(pengembalianPanel);
        pengembalianPanel.setLayout(pengembalianPanelLayout);
        pengembalianPanelLayout.setHorizontalGroup(
            pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengembalianPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(pengembalianLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pengembalianPanelLayout.setVerticalGroup(
            pengembalianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengembalianPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pengembalianLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        logoutPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutPanelMouseExited(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        logoutLabel.setText("LOGOUT");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout logoutPanelLayout = new javax.swing.GroupLayout(logoutPanel);
        logoutPanel.setLayout(logoutPanelLayout);
        logoutPanelLayout.setHorizontalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(logoutLabel)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        logoutPanelLayout.setVerticalGroup(
            logoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logoutLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mobilPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pengembalianPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(peminjamanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(mobilPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(pengembalianPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(peminjamanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(logoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputLabelMouseClicked
        // TODO add your handling code here:
        new inputpelanggan().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_inputLabelMouseClicked

    private void inputPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPanelMouseClicked
        // TODO add your handling code here:
        new inputpelanggan().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_inputPanelMouseClicked

    private void dataPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPanelMouseClicked
        // TODO add your handling code here:
        new datapelanggan().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_dataPanelMouseClicked

    private void inputPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPanelMouseEntered
        // TODO add your handling code here:
        inputPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_inputPanelMouseEntered

    private void inputPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPanelMouseExited
        // TODO add your handling code here:
        inputPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_inputPanelMouseExited

    private void dataPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPanelMouseEntered
        // TODO add your handling code here:
        dataPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_dataPanelMouseEntered

    private void dataPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPanelMouseExited
        // TODO add your handling code here:
        dataPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_dataPanelMouseExited

    private void dataLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataLabelMouseClicked
        // TODO add your handling code here:
        new datapelanggan().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_dataLabelMouseClicked

    private void inputLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputLabelMouseEntered
        // TODO add your handling code here:
        inputLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_inputLabelMouseEntered

    private void inputLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputLabelMouseExited
        // TODO add your handling code here:
        inputLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_inputLabelMouseExited

    private void dataLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataLabelMouseExited
        // TODO add your handling code here:
        dataLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_dataLabelMouseExited

    private void dataLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataLabelMouseEntered
        // TODO add your handling code here:
        dataLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_dataLabelMouseEntered

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Yakin mau logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            // Tindakan jika pengguna memilih "Ya"
            new login().setVisible(true);
            this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
        } else {
            // Tindakan jika pengguna memilih "Tidak" atau menutup dialog
            JOptionPane.showMessageDialog(null, "Logout dibatalkan.");
        }
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        // TODO add your handling code here:
        logoutLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        // TODO add your handling code here:
        logoutLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_logoutLabelMouseExited

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Yakin mau logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            // Tindakan jika pengguna memilih "Ya"
            new login().setVisible(true);
            this.dispose(); // Menutup frame Main_Menu1 saat frame Login ditampilkan
        } else {
            // Tindakan jika pengguna memilih "Tidak" atau menutup dialog
            JOptionPane.showMessageDialog(null, "Logout dibatalkan.");
        }
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void logoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseEntered
        // TODO add your handling code here:
        logoutPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutPanelMouseEntered

    private void logoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseExited
        // TODO add your handling code here:
        logoutPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_logoutPanelMouseExited

    private void mobilLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobilLabelMouseClicked
        // TODO add your handling code here:
        new datamobil().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_mobilLabelMouseClicked

    private void mobilLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobilLabelMouseEntered
        // TODO add your handling code here:
        mobilLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_mobilLabelMouseEntered

    private void mobilLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobilLabelMouseExited
        // TODO add your handling code here:
        mobilLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_mobilLabelMouseExited

    private void mobilPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobilPanelMouseClicked
        // TODO add your handling code here:
        new datamobil().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_mobilPanelMouseClicked

    private void mobilPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobilPanelMouseEntered
        // TODO add your handling code here:
        mobilPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_mobilPanelMouseEntered

    private void mobilPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobilPanelMouseExited
        // TODO add your handling code here:
        mobilPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_mobilPanelMouseExited

    private void peminjamanLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanLabelMouseClicked
        // TODO add your handling code here:
        new peminjamanUI().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_peminjamanLabelMouseClicked

    private void peminjamanLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanLabelMouseEntered
        // TODO add your handling code here:
        peminjamanLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_peminjamanLabelMouseEntered

    private void peminjamanLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanLabelMouseExited
        // TODO add your handling code here:
        peminjamanLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_peminjamanLabelMouseExited

    private void peminjamanPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanPanelMouseClicked
        // TODO add your handling code here:
        new peminjamanUI().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_peminjamanPanelMouseClicked

    private void peminjamanPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanPanelMouseEntered
        // TODO add your handling code here:
        peminjamanPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_peminjamanPanelMouseEntered

    private void peminjamanPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peminjamanPanelMouseExited
        // TODO add your handling code here:
        peminjamanPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_peminjamanPanelMouseExited

    private void pengembalianLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianLabelMouseClicked
        // TODO add your handling code here:
        new pengembalian().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_pengembalianLabelMouseClicked

    private void pengembalianLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianLabelMouseEntered
        // TODO add your handling code here:
        pengembalianLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pengembalianLabelMouseEntered

    private void pengembalianLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianLabelMouseExited
        // TODO add your handling code here:
        pengembalianLabel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pengembalianLabelMouseExited

    private void pengembalianPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianPanelMouseClicked
        // TODO add your handling code here:
        new pengembalian().setVisible(true);
        this.dispose(); // Menutup frame User saat frame Login ditampilkan
    }//GEN-LAST:event_pengembalianPanelMouseClicked

    private void pengembalianPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianPanelMouseEntered
        // TODO add your handling code here:
        pengembalianPanel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_pengembalianPanelMouseEntered

    private void pengembalianPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pengembalianPanelMouseExited
        // TODO add your handling code here:
        pengembalianPanel.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_pengembalianPanelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataLabel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JLabel mobilLabel;
    private javax.swing.JPanel mobilPanel;
    private javax.swing.JLabel peminjamanLabel;
    private javax.swing.JPanel peminjamanPanel;
    private javax.swing.JLabel pengembalianLabel;
    private javax.swing.JPanel pengembalianPanel;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
